# Generated by Django 6.0.2 on 2026-04-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_delete",
            field=models.BooleanField(default=False),
        ),
    ]
