# Generated by Django 6.0.2 on 2026-04-17 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_app", "0003_rating_avgrate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(upload_to="products/"),
        ),
    ]
