# Generated by Django 6.0.2 on 2026-04-17 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promocode",
            name="type",
            field=models.CharField(
                choices=[("flat", "flat"), ("percentage", "percentage")], max_length=50
            ),
        ),
    ]
