# Generated by Django 6.0.2 on 2026-04-09 14:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="otpverification",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 4, 9, 14, 30, 1, 20418, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AddField(
            model_name="otpverification",
            name="is_used",
            field=models.BooleanField(default=False),
        ),
    ]
