# Generated by Django 6.0.2 on 2026-04-13 12:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0002_otpverification_created_at_otpverification_is_used"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otpverification",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
